### ISSUE TITLE
Cli_example failing at stop when executed repeatedly

### ISSUE THREAD

**Issue by alejandrolabajos** [STMicroelectronics/fp-sns-datalog2#26]
Hello @pradolis 

I am trying to develop an autonomous vehicle based FSM using STEVAL-STWINBX1 with DATALOG2 (V3.0.0) to acquire data from almost all its sensors. 
Note: V2.3.0 and V2.2.0 also tested.

The first execution with cli_example works fine, but after the second execution, after stopping the datalog with keyboard (ESC) it gets hanged waiting for something to finish the execution. Working fine it takes 1-2 seconds to finish, when this thing occurs, waits hanged for about 15-20 sec and then starts throwing the same error in the terminal.
I am using a RaspberryPi 4 model B (tried with both, 32-bit and 64-bit OS).

Here is the explanation step by step.

RPi4B info:

![Image](https://github.com/user-attachments/assets/b2eddaa2-1d55-463c-a5bf-8ea6d97d11e5)

I followed the instructions explained in `README_raspberrypi.md` file, located at `/Utilities/cli_example`:

![Image](https://github.com/user-attachments/assets/f9ef63ca-c04f-44d9-9d7d-6386fc3696d8)

Everything works fine during ./setup script execution. I close this terminal and reopen a new one from `/cli_example/` folder following the instructions.

I ran `./bin_raspberryPi_32/cli_example` and as you can see is starting  and stopping perfectly:

![Image](https://github.com/user-attachments/assets/10e94069-21ce-4368-b202-0fc667860ed4)

![Image](https://github.com/user-attachments/assets/209d532c-69cb-438d-9184-4c8b7808b451)

Now I wait for arroud 10 seconds and, in the same console, I run again `./bin_raspberryPi_32/cli_example`. 
Works fine during datalogging but when I stop the the program hangs before ending execution:

![Image](https://github.com/user-attachments/assets/b4dc62ce-d55b-4f1d-8233-aa038d81b452)

And after 10-15 seconds being hanged, starts throwing errors:

![Image](https://github.com/user-attachments/assets/8825749a-e4cf-4f06-ae45-de56eb1eda1b)

I don't know what's happening but I think it's somehow related to error #22 because the output error is the same (not the format than @Ferag-AG but the same as @akashintera)

Many thanks!
Alex

**Comment by pradolis** [comment]
Hello,
let me first confirm that the issue seems related to Raspberry PI 4 only. I did some further tests on different Windows and Unix-based machines: there, the library seems to work properly.

The issue seems strictly related to the libusb library, used by our libhs_datalog_v2 to manage USB communication. 
While stopping an acquisition, sometimes the libusb_reset_device fails. We're still debugging the library and testing a patch.
The first step is to avoid USB block and at least avoid rebooting the system to have back a fully working setup.
The idea is to release a workaround where, during the stop procedure, the library releases the USB interface, closes the existing USB handle, reinitializes the USB context, and reconnects the USB device.

It is a work in progress, I'll continuously update you.

Best regards
Simone

**Comment by alejandrolabajos** [comment]
Hello @pradolis 

Yes, also from my side the library seems working fine on Windows.

Thank you for keeping me updated, I really apreciate it.

Regards,
Alex

**Comment by pradolis** [comment]
Hello,
we fixed the issue. [Here](https://github.com/user-attachments/files/19337598/bin_raspberryPi_64bit.zip) the updated cli_example + libhs_datalog_v2 for Raspberry 64bit.
Can you try it out?
If it is working properly also on your side, we'll push it on the repo.


Best regards
Simone

**Comment by alejandrolabajos** [comment]
Hello, 

In our RPi, when we first ran the new cli_example from the link above we've got this error regarding undefined symbols.

![Image](https://github.com/user-attachments/assets/6a401432-47ef-4ee1-a10c-481a942eb894)

But worked after we exported the library:

![Image](https://github.com/user-attachments/assets/774d9c6f-d954-4a78-98fd-4f75525575d1)

First execution taking data for about 12 sec finalyzed fine and fast after stopping it. Second execution too. 
But at third execution it got stucked after stopping it (not throwing that error message about libusb in the whole terminal but still frozen).  After a while, the terminal works again but then no detect the device anymore untill rpi is rebooted:

![Image](https://github.com/user-attachments/assets/3d7d4ca4-59ca-43f3-8256-66815cf5499c)


Note: We also tried to run cli_example with Linux-based OS from the device Nvidia AGX Orin 64GB, but seems it can't be run here probably because of architecture incompatibilites (Error: bash cannot execute binary file).

**Comment by akashintera** [comment]
I get this error  

![Image](https://github.com/user-attachments/assets/4145988f-2c4f-436e-91a2-8e095b1d1bf9)

**Comment by totino5** [comment]
Hi @pradolis, I noticed the same problem using stdatalog-pysdk, so now I'm stucked on a work project where I use both Raspberry PI Model 4 and STwin.box. Do you have any idea when the new version that fixes this bug might be released? 

Thank you!

**Comment by pradolis** [comment]
Hi all,
we finally solved a couple of bugs and installation misconfigurations strictly related to Raspberry Pi 4.
First, we improved libhs_datalog_v2.so.
Then, we found out that the USB communication issue is solved by updating the libusb version. Natively, Raspbian distribution installs an old libusb version (1.0.9 I guess). By manually installing more recent versions (1.0.27 or 1.0.28, the latest published few days ago) the issue disappears.
Furthermore, we added the support for MacOS also.

We are finally closing the internal validation in few days. Next week we'll share the updated libraries and python modules.

Thanks for you patience
Best regards
Simone

**Comment by totino5** [comment]
Hi @pradolis, thank you for your update. 

In my Raspberry PI configuration, I have the libusb 1.0.26 installed. The stdatalog gives the libusb error with this version so I tried to update to a newer one (1.0.28) following the github repo instructions. By launching this command after installation:

``` dpkg -l | grep libusb ```

I see this output:

``` 
ii  libgusb2:arm64                       0.3.10-1                            arm64        GLib wrapper around libusb1
ii  libusb-1.0-0:arm64                   2:1.0.26-1                          arm64        userspace USB programming library
ii  libusbmuxd6:arm64                    2.0.2-3                             arm64        USB multiplexor daemon for iPhone and iPod Touch devices - library
 ```

So the newer version isn't installed. Do you have some suggestions on how to update the library? Plus, will the USB communication issue be fixed with the next version of the libhs_datalog or it should be works even with the current versione of the libhs_datalog? 

Thank you!

**Comment by pradolis** [comment]
Hello @totino5 
We're publishing STDATALOG-PYSDK v1.1.0 that should automatically solve libusb dependency also. 

In the meanwhile, let me share here how I installed libusb on my Raspberry:
```
wget https://github.com/libusb/libusb/releases/download/v1.0.28/libusb-1.0.28.tar.bz2 
tar xjf libusb-1.0.28.tar.bz2 
cd libusb-1.0.28/ 
sudo apt-get install -y libudev-dev 
./configure 
sudo make install -j 4
```
Then, reboot the RPI. I replicated the same successfully with 3 different Raspberry (4 32bit, 4 64bit and 5 64bit).

Best regards
Simone

**Comment by pradolis** [comment]
Hi all,
@totino5: updated [STDATALOG-PYSDK](https://github.com/STMicroelectronics/stdatalog-pysdk) has been pushed few days ago. I've just added a couple of comments related to the instruction guide.

@alejandrolabajos @akashintera: I'm pushing the same DLL used in the python SDK and updated C++ cli_example and installers

Is this solving your issues? Can you provide me a feedback?
If I'll not receive any news in this week, I'll consider the issue solved, so I'll close it.

Best regards
Simone

**Comment by totino5** [comment]
Hi @pradolis,

I tried to update the repo via:

``` 
git pull
git submodule update --init --recursive
```
with no success, then I also formatted the SD card to proceed to a clean installation, but it still doesn't work. I will share some screens that resumes the errors I got:

1. When I launch:


``` 
cd linux_setup
dos2unix 30-hsdatalog.rules linux_USB_config_setup.sh linux_USB_config_removal.sh
chmod 777 linux_USB_config_setup.sh linux_USB_config_removal.sh
./linux_USB_config_setup.sh
``` 
I get these logs:

![Image](https://github.com/user-attachments/assets/a385b142-40da-4345-ae9a-8adf9901d370)

The last lines are strange:

> cp: cannot stat '../stdatalog_core/stdatalog_core/HSD_link/communication/libhs_datalog/raspberryPi4_64bit/libhs_datalog_v1.so': No such file or directory
cp: cannot stat '../stdatalog_core/stdatalog_core/HSD_link/communication/libhs_datalog/raspberryPi4_64bit/libhs_datalog_v2.so': No such file or directory
cp: cannot stat '30-hsdatalog.rules': No such file or directory


2.  When I launch:

``` 
source .venv/bin/activate
cd stdatalog_examples
python3 gui_applications/stdatalog/GUI/stdatalog_GUI.py
```
the communications between the sensor and the Raspberry seems to not work properly and it gives me this error:

![Image](https://github.com/user-attachments/assets/de68df5d-5733-4ea9-8278-045cf36e6c7f)

3. When I launch my custom program to start data acquisition, I get these logs:

![Image](https://github.com/user-attachments/assets/08a6343d-a767-4e11-9948-5c7afaf6be1c)

Thanks for your support!

**Comment by pradolis** [comment]
Hello @totino5 
if git commands are failing, it means you're not updating the sdk.
So, I can suppose you're still in trouble and all the rest of your comment are still related to an older instance of the sdk.
Are you sure git and access to github working properly on your machine?

Best regards
Simone

**Comment by totino5** [comment]
Hi @pradolis,

Sorry for my bad explanations. I was meaning that I tried to update the sdk with git and also tried to re-install the whole sdk (after format the SD card on Raspberry) following your instructions on the repo, but with both method the code execution gives me the errors above. I also re-tried a few minutes ago but I have the same problems.

Pretty sure that the sdk installed on my Raspberry is 1.1.0 because during the installation, log shows that the library is being uptdated to the new version. Also, re-launching 

```
git pull
git submodule update --init --recursive
```
I get:

```
Already up to date.
```

I tried on Windows machine and everything works fine.

P.S: I found out that you are italian like me, so if you want I can give you a better explanation of the problem in italian.

Thank you

**Comment by totino5** [comment]
Hi @pradolis, 
After inspecting all the operations during the installation of the SDK, I found out that in my case, when launching:

```
./linux_USB_config_setup.sh
```

the three files "libhs_datalog_v1.so", "libhs_datalog_v2.so" and "30-hsdatalog.rules" are not actually copied in the right folders specified by the "cp" command (please look at the first picture in the comment above). In fact, the log reports:

```
cp: cannot stat '../stdatalog_core/stdatalog_core/HSD_link/communication/libhs_datalog/raspberryPi4_64bit/libhs_datalog_v1.so': No such file or directory
cp: cannot stat '../stdatalog_core/stdatalog_core/HSD_link/communication/libhs_datalog/raspberryPi4_64bit/libhs_datalog_v2.so': No such file or directory
cp: cannot stat '30-hsdatalog.rules': No such file or directory
```

By manually launching these commands specified in "./linux_USB_config_setup.sh":
```
sudo cp ../stdatalog_core/stdatalog_core/HSD_link/communication/libhs_datalog/raspberryPi4_64bit/libhs_datalog_v1.so /usr/lib
sudo cp ../stdatalog_core/stdatalog_core/HSD_link/communication/libhs_datalog/raspberryPi4_64bit/libhs_datalog_v2.so /usr/lib
sudo cp 30-hsdatalog.rules /etc/udev/rules.d
```
the SDK is correctly installed and also the GUI applications works fine.


Unfortunally, I have another issue. When starting and stopping multiple consecutive acquisitions via the SensorAcquisitionThread (following "nb_stdatalog_communication.ipynb"), the program crashes after a number of acquisitions (it's variable but it will crashes) with the following log:

![Image](https://github.com/user-attachments/assets/ab144f2c-ec2d-4a5d-b116-ae989949aeef)

Then, when trying to re-launch my program, the acquisition doesn't start at all, showing this:

![Image](https://github.com/user-attachments/assets/d40a13f3-1565-486c-8555-29bb783489c7)

You can find my sensor acquistion program below. Then, this program is called by another script that sends messages over the cloud.

Thank you.

sensor_acquisition.py 
```
from stdatalog_core.HSD_link.HSDLink import HSDLink, SensorAcquisitionThread
from stdatalog_core.HSD.HSDatalog import HSDatalog
import time
import os
import statistics
from threading import Event

threads_stop_flags = []
sensor_data_files = []

def sensor_acquisition_function(acquisition_folder, device_id):
    # Check if parameters are provided
    if(acquisition_folder == '' or device_id is None):
        print("\nAcquisition folder or device id not provided! Exiting...\n")
        return

    # Create HSDLink instance
    hsd_link = HSDLink()
    hsd_link_instance = hsd_link.create_hsd_link(dev_com_type="st_hsd", acquisition_folder=acquisition_folder)

    # Get device
    device = hsd_link.get_device(hsd_link_instance, device_id)
    device_alias = hsd_link.get_device_alias(hsd_link_instance, device_id)
    print(f"\nDevice Alias: {device_alias}\n")

    # Initialize HSD
    hsd = HSDatalog()
    hsd_instance = hsd.create_hsd(device_config = device)
    HSDatalog.set_device(hsd_instance, device)

    # Get sensor list
    sensor_list = hsd_link.get_sensor_list(hsd_link_instance, device_id, only_active=True)

    # Set date and time on device
    hsd_link.set_RTC(hsd_link_instance, device_id)

    # Initialize HSD Link Log
    hsd_link.start_log(hsd_link_instance, device_id)

    # Start the acquisition process
    # Get all sensors
    for sensor_name in sensor_list:
        # Verify if sensor is enabled
        is_enabled = hsd_link.get_sensor_enabled(hsd_link_instance, device_id, sensor_name)
        if is_enabled:
            # Create acquisition file path 
            sensor_data_file_path = os.path.join(hsd_link.get_acquisition_folder(hsd_link_instance), f"{sensor_name}.dat")
            # Open file
            sensor_data_file = open(sensor_data_file_path, "wb+")
            # Append file to files list
            sensor_data_files.append(sensor_data_file)
            # Define stopFlag to end the acquisition process
            stopFlag = Event()
            # Append stopFlag to stop flags list
            threads_stop_flags.append(stopFlag)
            # Start the acquisition process
            thread = SensorAcquisitionThread(stopFlag, hsd_link_instance, sensor_data_file, device_id, sensor_name)
            thread.start()
        else:
            print(f"\nSensor {sensor_name} is not enabled.\n")
            

    # Dummy sleep
    print("\nWaiting for 3 seconds before stopping the acquisition...\n")
    time.sleep(3)

    # Stop the acquisition process
    for stopFlag in threads_stop_flags:
        stopFlag.set()

    # Close files
    for file in sensor_data_files:
        file.close()

    print("\nWaiting for 3 seconds before stopping...\n")
    time.sleep(3)
    
    # Close log and save device and acquisition info files
    hsd_link.stop_log(hsd_link_instance, device_id)
    hsd_link.save_json_device_file(hsd_link_instance, device_id)
    hsd_link.save_json_acq_info_file(hsd_link_instance, device_id)


    # Update the hsd_instance with the new acquisition folder 
    hsd_instance = hsd.create_hsd(acquisition_folder=hsd_link.get_acquisition_folder(hsd_link_instance))
    hsd_link_instance.close()

    # Calculate the mean for every sensor and store it in a dictionary
    mean_data_dictionary = {}
    for sensor_name in sensor_list:
        sensor = hsd.get_sensor(hsd_instance, sensor_name)
        dataframes = hsd.get_dataframe_gen(hsd_instance, sensor)
        for df in dataframes:
            # Delete time colunm on dataframe
            df = df.drop("Time", axis=1)
            for col in df.columns:
                mean = statistics.mean(df[col])
                measure_name = str(df[col].name).split(" ")[0] + "_" + sensor_name
                mean_data_dictionary[measure_name] = mean

    print("\nAcquisition completed!\n")

    return mean_data_dictionary

```

**Comment by alejandrolabajos** [comment]
Hello @pradolis 

Installation of new `setup.sh` worked fine with no errors, but when I run `cli_example` I get this error regarding GLIBCXX and GLIBC:

![Image](https://github.com/user-attachments/assets/b072f440-3801-46a8-8cbf-fe20b64b10ec)

Checking this library you can see that there is no version 3.4.29, which is the one giving error:

![Image](https://github.com/user-attachments/assets/032f199d-0b65-4aa4-8b3a-841c4b04ae4e)

Should I need to install something else or some change is needed inside installation script?

Thank you,
Alex

**Comment by pradolis** [comment]
Hello @alejandrolabajos 
Here a screenshot from my RPI4 32 bit environment:

![Image](https://github.com/user-attachments/assets/6237a237-4b6d-4818-85d9-e7c59c939465)

I installed a fresh distribution  more or less one month ago and a more recent GLIB library was already available.
I guess that upgrade-update your environment should solve your issue

**Comment by pradolis** [comment]
Hello @totino5 

> [...] 
> Unfortunally, I have another issue. When starting and stopping multiple consecutive acquisitions via the SensorAcquisitionThread (following "nb_stdatalog_communication.ipynb"), the program crashes after a number of acquisitions (it's variable but it will crashes) with the following log:
> 
> ![Image](https://github.com/user-attachments/assets/ab144f2c-ec2d-4a5d-b116-ae989949aeef)

Is the led blinking? I guess no, so the firmware crashed and consequently USB communication is failing definitively.
Can you remember me which board, firmware and version you are using?

> [...]
> Then, when trying to re-launch my program, the acquisition doesn't start at all, showing this:
> 
> ![Image](https://github.com/user-attachments/assets/d40a13f3-1565-486c-8555-29bb783489c7)

The board and the USB are already dead. You can't restart anymore. If you are in this situation, there’s no other way than reboot the board and the USB on your RPI.

**Comment by totino5** [comment]
Hello @pradolis,

Yes, both green and red led are blinking, even after the program crashes.
 
I am using STEVAL-STWINBX1 flashed with the "fp-sns-datalog2" firmware version 3.0.0.

**Comment by totino5** [comment]
Hi @pradolis, any news about the issues? Have you been able to reproduce? 

If you want more informations, we can also talk to each other in private so you can have a clear overview of the situation.

**Comment by totino5** [comment]
Hi @pradolis, are there any news about the issue? 

I use the sensor in a work project with my company and we need updates because we want to retrieve some data on a vehicle and then send them to the cloud. We have a Raspberry 4 for the development but we are looking to buy a Raspberry 5 for the production environment. Do you know if the library works properly with RPi 5?

**Comment by akashintera** [comment]
any update @pradolis ?

**Comment by alejandrolabajos** [comment]
Hello @pradolis 

I tested it with a brand new RPI4B flashed with latest 64-bit OS. 

Glibc error does not appear anymore (I think was related to 32-bit RPI OS). Despite this, when I ran cli_example, the script behaves the same way as the top of the issue: 
a) execute cli_example 1st time -> wait 10 sec -> press ESC -> program ends OK (in 1-2 sec).
b) wait some seconds -> repeat steps of a) -> same behaviour as described at top (exit gets hang out for 15-20 sec and then error of HSD_DLLv2 - image below)

![Image](https://github.com/user-attachments/assets/add7aaa5-288a-4964-aca2-6a0d9a224ebc)

I also tried to update libusb-1.0.28 but nothing worked.

Many thanks,
Alex

**Comment by akashintera** [comment]
Do you plan to push a new version @pradolis  ?

**Comment by alejandrolabajos** [comment]
Hello @pradolis 

Any update on this issue? Do you have internally some roadmap for releasing a new version? We still need it for a project and would be nice to skip this error.

Thank you so much!
Alex

**Comment by akashintera** [comment]
Still the same issue !!


<img width="2353" height="1241" alt="Image" src="https://github.com/user-attachments/assets/6e542bb2-0bc6-42e2-8d59-0440c01ce553" />


<img width="1604" height="795" alt="Image" src="https://github.com/user-attachments/assets/ead323a1-6b0c-4148-8ac6-17be4fda4335" />

**Comment by akashintera** [comment]
I made it work by connecting the STWIN using an fast charging USB hub.

**Comment by pradolis** [comment]
Let me add a couple of further comments on the topic.
I've always used both RPI4 and 5 with an original power supply (15W and 27W respectively). I'm guessing, but if USB isn’t working properly on the RPI side due to some power issues, maybe that's why I've never got your issues anymore. This can't be controlled by both cli_example either PYSDK.
Furthermore, specifically for STWIN board (STEVAL-STWINKT1B), thanks to the contribution of a customer on community ([link](https://community.st.com/t5/stm32-mcus-boards-and-hardware/stwinkt1b-pysdk-can-no-longer-connect/m-p/857519)), I found out a bug in DATALOG2 firmware. See the link for further details; the upcoming v3.2.0 DATALOG2 firmware will solve the issue.

Now, I'm closing the issue. Both FP-SNS-DATALOG2 and STDATALOG-PYSDK updated releases are coming soon.
If you need further support or new suggestions, open new issues in the related repositories.
